// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/hook/product.proto

package hook

import (
	data "github.com/crevendo/crevendo/data"
	message "github.com/crevendo/crevendo/message"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductListHookParams struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Products      []*data.Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Message       *message.ProductListMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductListHookParams) Reset() {
	*x = ProductListHookParams{}
	mi := &file_proto_hook_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductListHookParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductListHookParams) ProtoMessage() {}

func (x *ProductListHookParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hook_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductListHookParams.ProtoReflect.Descriptor instead.
func (*ProductListHookParams) Descriptor() ([]byte, []int) {
	return file_proto_hook_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductListHookParams) GetProducts() []*data.Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ProductListHookParams) GetMessage() *message.ProductListMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type ProductGetHookParams struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Product       *data.Product              `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Message       *message.ProductGetMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductGetHookParams) Reset() {
	*x = ProductGetHookParams{}
	mi := &file_proto_hook_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductGetHookParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductGetHookParams) ProtoMessage() {}

func (x *ProductGetHookParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hook_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductGetHookParams.ProtoReflect.Descriptor instead.
func (*ProductGetHookParams) Descriptor() ([]byte, []int) {
	return file_proto_hook_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductGetHookParams) GetProduct() *data.Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *ProductGetHookParams) GetMessage() *message.ProductGetMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_proto_hook_product_proto protoreflect.FileDescriptor

const file_proto_hook_product_proto_rawDesc = "" +
	"\n" +
	"\x18proto/hook/product.proto\x1a\x13proto/product.proto\x1a\x1bproto/message/product.proto\"l\n" +
	"\x15ProductListHookParams\x12$\n" +
	"\bproducts\x18\x01 \x03(\v2\b.ProductR\bproducts\x12-\n" +
	"\amessage\x18\x02 \x01(\v2\x13.ProductListMessageR\amessage\"h\n" +
	"\x14ProductGetHookParams\x12\"\n" +
	"\aproduct\x18\x01 \x01(\v2\b.ProductR\aproduct\x12,\n" +
	"\amessage\x18\x02 \x01(\v2\x12.ProductGetMessageR\amessage2\x8d\x01\n" +
	"\fProductHooks\x12?\n" +
	"\vProductList\x12\x16.ProductListHookParams\x1a\x16.ProductListHookParams\"\x00\x12<\n" +
	"\n" +
	"ProductGet\x12\x15.ProductGetHookParams\x1a\x15.ProductGetHookParams\"\x00B#Z!github.com/crevendo/crevendo/hookb\x06proto3"

var (
	file_proto_hook_product_proto_rawDescOnce sync.Once
	file_proto_hook_product_proto_rawDescData []byte
)

func file_proto_hook_product_proto_rawDescGZIP() []byte {
	file_proto_hook_product_proto_rawDescOnce.Do(func() {
		file_proto_hook_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hook_product_proto_rawDesc), len(file_proto_hook_product_proto_rawDesc)))
	})
	return file_proto_hook_product_proto_rawDescData
}

var file_proto_hook_product_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_hook_product_proto_goTypes = []any{
	(*ProductListHookParams)(nil),      // 0: ProductListHookParams
	(*ProductGetHookParams)(nil),       // 1: ProductGetHookParams
	(*data.Product)(nil),               // 2: Product
	(*message.ProductListMessage)(nil), // 3: ProductListMessage
	(*message.ProductGetMessage)(nil),  // 4: ProductGetMessage
}
var file_proto_hook_product_proto_depIdxs = []int32{
	2, // 0: ProductListHookParams.products:type_name -> Product
	3, // 1: ProductListHookParams.message:type_name -> ProductListMessage
	2, // 2: ProductGetHookParams.product:type_name -> Product
	4, // 3: ProductGetHookParams.message:type_name -> ProductGetMessage
	0, // 4: ProductHooks.ProductList:input_type -> ProductListHookParams
	1, // 5: ProductHooks.ProductGet:input_type -> ProductGetHookParams
	0, // 6: ProductHooks.ProductList:output_type -> ProductListHookParams
	1, // 7: ProductHooks.ProductGet:output_type -> ProductGetHookParams
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_hook_product_proto_init() }
func file_proto_hook_product_proto_init() {
	if File_proto_hook_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hook_product_proto_rawDesc), len(file_proto_hook_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hook_product_proto_goTypes,
		DependencyIndexes: file_proto_hook_product_proto_depIdxs,
		MessageInfos:      file_proto_hook_product_proto_msgTypes,
	}.Build()
	File_proto_hook_product_proto = out.File
	file_proto_hook_product_proto_goTypes = nil
	file_proto_hook_product_proto_depIdxs = nil
}
