// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/service/category.proto

package grpc

import (
	message "github.com/crevendo/crevendo/message"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_service_category_proto protoreflect.FileDescriptor

const file_proto_service_category_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/service/category.proto\x1a\x1cproto/message/category.proto2\xb3\x02\n" +
	"\x0fCategoryService\x122\n" +
	"\x03Get\x12\x13.CategoryGetMessage\x1a\x14.CategoryGetResponse\"\x00\x125\n" +
	"\x04List\x12\x14.CategoryListMessage\x1a\x15.CategoryListResponse\"\x00\x12;\n" +
	"\x06Create\x12\x16.CategoryCreateMessage\x1a\x17.CategoryCreateResponse\"\x00\x12;\n" +
	"\x06Update\x12\x16.CategoryUpdateMessage\x1a\x17.CategoryUpdateResponse\"\x00\x12;\n" +
	"\x06Delete\x12\x16.CategoryDeleteMessage\x1a\x17.CategoryDeleteResponse\"\x00B#Z!github.com/crevendo/crevendo/grpcb\x06proto3"

var file_proto_service_category_proto_goTypes = []any{
	(*message.CategoryGetMessage)(nil),     // 0: CategoryGetMessage
	(*message.CategoryListMessage)(nil),    // 1: CategoryListMessage
	(*message.CategoryCreateMessage)(nil),  // 2: CategoryCreateMessage
	(*message.CategoryUpdateMessage)(nil),  // 3: CategoryUpdateMessage
	(*message.CategoryDeleteMessage)(nil),  // 4: CategoryDeleteMessage
	(*message.CategoryGetResponse)(nil),    // 5: CategoryGetResponse
	(*message.CategoryListResponse)(nil),   // 6: CategoryListResponse
	(*message.CategoryCreateResponse)(nil), // 7: CategoryCreateResponse
	(*message.CategoryUpdateResponse)(nil), // 8: CategoryUpdateResponse
	(*message.CategoryDeleteResponse)(nil), // 9: CategoryDeleteResponse
}
var file_proto_service_category_proto_depIdxs = []int32{
	0, // 0: CategoryService.Get:input_type -> CategoryGetMessage
	1, // 1: CategoryService.List:input_type -> CategoryListMessage
	2, // 2: CategoryService.Create:input_type -> CategoryCreateMessage
	3, // 3: CategoryService.Update:input_type -> CategoryUpdateMessage
	4, // 4: CategoryService.Delete:input_type -> CategoryDeleteMessage
	5, // 5: CategoryService.Get:output_type -> CategoryGetResponse
	6, // 6: CategoryService.List:output_type -> CategoryListResponse
	7, // 7: CategoryService.Create:output_type -> CategoryCreateResponse
	8, // 8: CategoryService.Update:output_type -> CategoryUpdateResponse
	9, // 9: CategoryService.Delete:output_type -> CategoryDeleteResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_service_category_proto_init() }
func file_proto_service_category_proto_init() {
	if File_proto_service_category_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_category_proto_rawDesc), len(file_proto_service_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_category_proto_goTypes,
		DependencyIndexes: file_proto_service_category_proto_depIdxs,
	}.Build()
	File_proto_service_category_proto = out.File
	file_proto_service_category_proto_goTypes = nil
	file_proto_service_category_proto_depIdxs = nil
}
