// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/service/event.proto

package grpc

import (
	message "github.com/crevendo/crevendo/message"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_service_event_proto protoreflect.FileDescriptor

const file_proto_service_event_proto_rawDesc = "" +
	"\n" +
	"\x19proto/service/event.proto\x1a\x19proto/message/event.proto2v\n" +
	"\fEventService\x125\n" +
	"\x06Create\x12\x13.EventCreateRequest\x1a\x14.EventCreateResponse\"\x00\x12/\n" +
	"\x04List\x12\x11.EventListRequest\x1a\x12.EventListResponse\"\x00B#Z!github.com/crevendo/crevendo/grpcb\x06proto3"

var file_proto_service_event_proto_goTypes = []any{
	(*message.EventCreateRequest)(nil),  // 0: EventCreateRequest
	(*message.EventListRequest)(nil),    // 1: EventListRequest
	(*message.EventCreateResponse)(nil), // 2: EventCreateResponse
	(*message.EventListResponse)(nil),   // 3: EventListResponse
}
var file_proto_service_event_proto_depIdxs = []int32{
	0, // 0: EventService.Create:input_type -> EventCreateRequest
	1, // 1: EventService.List:input_type -> EventListRequest
	2, // 2: EventService.Create:output_type -> EventCreateResponse
	3, // 3: EventService.List:output_type -> EventListResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_service_event_proto_init() }
func file_proto_service_event_proto_init() {
	if File_proto_service_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_event_proto_rawDesc), len(file_proto_service_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_event_proto_goTypes,
		DependencyIndexes: file_proto_service_event_proto_depIdxs,
	}.Build()
	File_proto_service_event_proto = out.File
	file_proto_service_event_proto_goTypes = nil
	file_proto_service_event_proto_depIdxs = nil
}
