// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/service/product.proto

package grpc

import (
	message "github.com/crevendo/crevendo/message"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_service_product_proto protoreflect.FileDescriptor

const file_proto_service_product_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/service/product.proto\x1a\x1bproto/message/product.proto2\xa8\x02\n" +
	"\x0eProductService\x120\n" +
	"\x03Get\x12\x12.ProductGetMessage\x1a\x13.ProductGetResponse\"\x00\x123\n" +
	"\x04List\x12\x13.ProductListMessage\x1a\x14.ProductListResponse\"\x00\x129\n" +
	"\x06Update\x12\x15.ProductUpdateMessage\x1a\x16.ProductUpdateResponse\"\x00\x129\n" +
	"\x06Create\x12\x15.ProductCreateMessage\x1a\x16.ProductCreateResponse\"\x00\x129\n" +
	"\x06Delete\x12\x15.ProductDeleteMessage\x1a\x16.ProductDeleteResponse\"\x00B#Z!github.com/crevendo/crevendo/grpcb\x06proto3"

var file_proto_service_product_proto_goTypes = []any{
	(*message.ProductGetMessage)(nil),     // 0: ProductGetMessage
	(*message.ProductListMessage)(nil),    // 1: ProductListMessage
	(*message.ProductUpdateMessage)(nil),  // 2: ProductUpdateMessage
	(*message.ProductCreateMessage)(nil),  // 3: ProductCreateMessage
	(*message.ProductDeleteMessage)(nil),  // 4: ProductDeleteMessage
	(*message.ProductGetResponse)(nil),    // 5: ProductGetResponse
	(*message.ProductListResponse)(nil),   // 6: ProductListResponse
	(*message.ProductUpdateResponse)(nil), // 7: ProductUpdateResponse
	(*message.ProductCreateResponse)(nil), // 8: ProductCreateResponse
	(*message.ProductDeleteResponse)(nil), // 9: ProductDeleteResponse
}
var file_proto_service_product_proto_depIdxs = []int32{
	0, // 0: ProductService.Get:input_type -> ProductGetMessage
	1, // 1: ProductService.List:input_type -> ProductListMessage
	2, // 2: ProductService.Update:input_type -> ProductUpdateMessage
	3, // 3: ProductService.Create:input_type -> ProductCreateMessage
	4, // 4: ProductService.Delete:input_type -> ProductDeleteMessage
	5, // 5: ProductService.Get:output_type -> ProductGetResponse
	6, // 6: ProductService.List:output_type -> ProductListResponse
	7, // 7: ProductService.Update:output_type -> ProductUpdateResponse
	8, // 8: ProductService.Create:output_type -> ProductCreateResponse
	9, // 9: ProductService.Delete:output_type -> ProductDeleteResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_service_product_proto_init() }
func file_proto_service_product_proto_init() {
	if File_proto_service_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_product_proto_rawDesc), len(file_proto_service_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_product_proto_goTypes,
		DependencyIndexes: file_proto_service_product_proto_depIdxs,
	}.Build()
	File_proto_service_product_proto = out.File
	file_proto_service_product_proto_goTypes = nil
	file_proto_service_product_proto_depIdxs = nil
}
