// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/service/session.proto

package grpc

import (
	message "github.com/crevendo/crevendo/message"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_service_session_proto protoreflect.FileDescriptor

const file_proto_service_session_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/service/session.proto\x1a\x1bproto/message/session.proto2}\n" +
	"\x0eSessionService\x120\n" +
	"\x03Get\x12\x12.SessionGetMessage\x1a\x13.SessionGetResponse\"\x00\x129\n" +
	"\x06Create\x12\x15.SessionCreateMessage\x1a\x16.SessionCreateResponse\"\x00B#Z!github.com/crevendo/crevendo/grpcb\x06proto3"

var file_proto_service_session_proto_goTypes = []any{
	(*message.SessionGetMessage)(nil),     // 0: SessionGetMessage
	(*message.SessionCreateMessage)(nil),  // 1: SessionCreateMessage
	(*message.SessionGetResponse)(nil),    // 2: SessionGetResponse
	(*message.SessionCreateResponse)(nil), // 3: SessionCreateResponse
}
var file_proto_service_session_proto_depIdxs = []int32{
	0, // 0: SessionService.Get:input_type -> SessionGetMessage
	1, // 1: SessionService.Create:input_type -> SessionCreateMessage
	2, // 2: SessionService.Get:output_type -> SessionGetResponse
	3, // 3: SessionService.Create:output_type -> SessionCreateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_service_session_proto_init() }
func file_proto_service_session_proto_init() {
	if File_proto_service_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_session_proto_rawDesc), len(file_proto_service_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_session_proto_goTypes,
		DependencyIndexes: file_proto_service_session_proto_depIdxs,
	}.Build()
	File_proto_service_session_proto = out.File
	file_proto_service_session_proto_goTypes = nil
	file_proto_service_session_proto_depIdxs = nil
}
