// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/message/auth.proto

package message

import (
	data "github.com/crevendo/crevendo/data"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginMessage) Reset() {
	*x = LoginMessage{}
	mi := &file_proto_message_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginMessage) ProtoMessage() {}

func (x *LoginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginMessage.ProtoReflect.Descriptor instead.
func (*LoginMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_message_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type QuickLoginMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuickLoginMessage) Reset() {
	*x = QuickLoginMessage{}
	mi := &file_proto_message_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuickLoginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickLoginMessage) ProtoMessage() {}

func (x *QuickLoginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickLoginMessage.ProtoReflect.Descriptor instead.
func (*QuickLoginMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_auth_proto_rawDescGZIP(), []int{2}
}

func (x *QuickLoginMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type QuickLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuickLoginResponse) Reset() {
	*x = QuickLoginResponse{}
	mi := &file_proto_message_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuickLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickLoginResponse) ProtoMessage() {}

func (x *QuickLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickLoginResponse.ProtoReflect.Descriptor instead.
func (*QuickLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_auth_proto_rawDescGZIP(), []int{3}
}

func (x *QuickLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FirstName         string                 `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName          string                 `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Username          string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email             string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password          string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Fields            []*data.Field          `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	IsQuick           bool                   `protobuf:"varint,7,opt,name=isQuick,proto3" json:"isQuick,omitempty"`
	ChangePasswordUrl *string                `protobuf:"bytes,8,opt,name=changePasswordUrl,proto3,oneof" json:"changePasswordUrl,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterMessage) Reset() {
	*x = RegisterMessage{}
	mi := &file_proto_message_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMessage) ProtoMessage() {}

func (x *RegisterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMessage.ProtoReflect.Descriptor instead.
func (*RegisterMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterMessage) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterMessage) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterMessage) GetFields() []*data.Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *RegisterMessage) GetIsQuick() bool {
	if x != nil {
		return x.IsQuick
	}
	return false
}

func (x *RegisterMessage) GetChangePasswordUrl() string {
	if x != nil && x.ChangePasswordUrl != nil {
		return *x.ChangePasswordUrl
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_message_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_auth_proto_rawDescGZIP(), []int{5}
}

type VerifyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyMessage) Reset() {
	*x = VerifyMessage{}
	mi := &file_proto_message_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMessage) ProtoMessage() {}

func (x *VerifyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMessage.ProtoReflect.Descriptor instead.
func (*VerifyMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_auth_proto_rawDescGZIP(), []int{6}
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *data.User             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_proto_message_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_auth_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyResponse) GetUser() *data.User {
	if x != nil {
		return x.User
	}
	return nil
}

type ForgotPasswordMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordMessage) Reset() {
	*x = ForgotPasswordMessage{}
	mi := &file_proto_message_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordMessage) ProtoMessage() {}

func (x *ForgotPasswordMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordMessage.ProtoReflect.Descriptor instead.
func (*ForgotPasswordMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ForgotPasswordMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ForgotPasswordMessage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ForgotPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordResponse) Reset() {
	*x = ForgotPasswordResponse{}
	mi := &file_proto_message_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordResponse) ProtoMessage() {}

func (x *ForgotPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordResponse.ProtoReflect.Descriptor instead.
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_auth_proto_rawDescGZIP(), []int{9}
}

type ResetPasswordMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordMessage) Reset() {
	*x = ResetPasswordMessage{}
	mi := &file_proto_message_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordMessage) ProtoMessage() {}

func (x *ResetPasswordMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordMessage.ProtoReflect.Descriptor instead.
func (*ResetPasswordMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ResetPasswordMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetPasswordMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_proto_message_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_auth_proto_rawDescGZIP(), []int{11}
}

var File_proto_message_auth_proto protoreflect.FileDescriptor

const file_proto_message_auth_proto_rawDesc = "" +
	"\n" +
	"\x18proto/message/auth.proto\x1a\x14proto/validate.proto\x1a\x10proto/user.proto\x1a\x11proto/field.proto\"X\n" +
	"\fLoginMessage\x12#\n" +
	"\busername\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\busername\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"8\n" +
	"\x11QuickLoginMessage\x12#\n" +
	"\busername\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\busername\"*\n" +
	"\x12QuickLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x9c\x02\n" +
	"\x0fRegisterMessage\x12\x1c\n" +
	"\tfirstName\x18\x01 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x02 \x01(\tR\blastName\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1e\n" +
	"\x06fields\x18\x06 \x03(\v2\x06.FieldR\x06fields\x12\x18\n" +
	"\aisQuick\x18\a \x01(\bR\aisQuick\x121\n" +
	"\x11changePasswordUrl\x18\b \x01(\tH\x00R\x11changePasswordUrl\x88\x01\x01B\x14\n" +
	"\x12_changePasswordUrl\"\x12\n" +
	"\x10RegisterResponse\"\x0f\n" +
	"\rVerifyMessage\"+\n" +
	"\x0eVerifyResponse\x12\x19\n" +
	"\x04user\x18\x01 \x01(\v2\x05.UserR\x04user\"?\n" +
	"\x15ForgotPasswordMessage\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\x18\n" +
	"\x16ForgotPasswordResponse\"H\n" +
	"\x14ResetPasswordMessage\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x17\n" +
	"\x15ResetPasswordResponseB&Z$github.com/crevendo/crevendo/messageb\x06proto3"

var (
	file_proto_message_auth_proto_rawDescOnce sync.Once
	file_proto_message_auth_proto_rawDescData []byte
)

func file_proto_message_auth_proto_rawDescGZIP() []byte {
	file_proto_message_auth_proto_rawDescOnce.Do(func() {
		file_proto_message_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_auth_proto_rawDesc), len(file_proto_message_auth_proto_rawDesc)))
	})
	return file_proto_message_auth_proto_rawDescData
}

var file_proto_message_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_message_auth_proto_goTypes = []any{
	(*LoginMessage)(nil),           // 0: LoginMessage
	(*LoginResponse)(nil),          // 1: LoginResponse
	(*QuickLoginMessage)(nil),      // 2: QuickLoginMessage
	(*QuickLoginResponse)(nil),     // 3: QuickLoginResponse
	(*RegisterMessage)(nil),        // 4: RegisterMessage
	(*RegisterResponse)(nil),       // 5: RegisterResponse
	(*VerifyMessage)(nil),          // 6: VerifyMessage
	(*VerifyResponse)(nil),         // 7: VerifyResponse
	(*ForgotPasswordMessage)(nil),  // 8: ForgotPasswordMessage
	(*ForgotPasswordResponse)(nil), // 9: ForgotPasswordResponse
	(*ResetPasswordMessage)(nil),   // 10: ResetPasswordMessage
	(*ResetPasswordResponse)(nil),  // 11: ResetPasswordResponse
	(*data.Field)(nil),             // 12: Field
	(*data.User)(nil),              // 13: User
}
var file_proto_message_auth_proto_depIdxs = []int32{
	12, // 0: RegisterMessage.fields:type_name -> Field
	13, // 1: VerifyResponse.user:type_name -> User
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_message_auth_proto_init() }
func file_proto_message_auth_proto_init() {
	if File_proto_message_auth_proto != nil {
		return
	}
	file_proto_message_auth_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_auth_proto_rawDesc), len(file_proto_message_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_message_auth_proto_goTypes,
		DependencyIndexes: file_proto_message_auth_proto_depIdxs,
		MessageInfos:      file_proto_message_auth_proto_msgTypes,
	}.Build()
	File_proto_message_auth_proto = out.File
	file_proto_message_auth_proto_goTypes = nil
	file_proto_message_auth_proto_depIdxs = nil
}
