// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/message/brand.proto

package message

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BrandListMessage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *BrandListMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BrandListMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BrandListMessageMultiError, or nil if none found.
func (m *BrandListMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *BrandListMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return BrandListMessageMultiError(errors)
	}

	return nil
}

// BrandListMessageMultiError is an error wrapping multiple validation errors
// returned by BrandListMessage.ValidateAll() if the designated constraints
// aren't met.
type BrandListMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BrandListMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BrandListMessageMultiError) AllErrors() []error { return m }

// BrandListMessageValidationError is the validation error returned by
// BrandListMessage.Validate if the designated constraints aren't met.
type BrandListMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BrandListMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BrandListMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BrandListMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BrandListMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BrandListMessageValidationError) ErrorName() string { return "BrandListMessageValidationError" }

// Error satisfies the builtin error interface
func (e BrandListMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBrandListMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BrandListMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BrandListMessageValidationError{}

// Validate checks the field values on BrandListResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *BrandListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BrandListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BrandListResponseMultiError, or nil if none found.
func (m *BrandListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BrandListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBrands() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BrandListResponseValidationError{
						field:  fmt.Sprintf("Brands[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BrandListResponseValidationError{
						field:  fmt.Sprintf("Brands[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BrandListResponseValidationError{
					field:  fmt.Sprintf("Brands[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return BrandListResponseMultiError(errors)
	}

	return nil
}

// BrandListResponseMultiError is an error wrapping multiple validation errors
// returned by BrandListResponse.ValidateAll() if the designated constraints
// aren't met.
type BrandListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BrandListResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BrandListResponseMultiError) AllErrors() []error { return m }

// BrandListResponseValidationError is the validation error returned by
// BrandListResponse.Validate if the designated constraints aren't met.
type BrandListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BrandListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BrandListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BrandListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BrandListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BrandListResponseValidationError) ErrorName() string {
	return "BrandListResponseValidationError"
}

// Error satisfies the builtin error interface
func (e BrandListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBrandListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BrandListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BrandListResponseValidationError{}

// Validate checks the field values on BrandGetMessage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *BrandGetMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BrandGetMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BrandGetMessageMultiError, or nil if none found.
func (m *BrandGetMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *BrandGetMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return BrandGetMessageMultiError(errors)
	}

	return nil
}

// BrandGetMessageMultiError is an error wrapping multiple validation errors
// returned by BrandGetMessage.ValidateAll() if the designated constraints
// aren't met.
type BrandGetMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BrandGetMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BrandGetMessageMultiError) AllErrors() []error { return m }

// BrandGetMessageValidationError is the validation error returned by
// BrandGetMessage.Validate if the designated constraints aren't met.
type BrandGetMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BrandGetMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BrandGetMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BrandGetMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BrandGetMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BrandGetMessageValidationError) ErrorName() string { return "BrandGetMessageValidationError" }

// Error satisfies the builtin error interface
func (e BrandGetMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBrandGetMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BrandGetMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BrandGetMessageValidationError{}

// Validate checks the field values on BrandGetResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *BrandGetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BrandGetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BrandGetResponseMultiError, or nil if none found.
func (m *BrandGetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BrandGetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetBrand()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BrandGetResponseValidationError{
					field:  "Brand",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BrandGetResponseValidationError{
					field:  "Brand",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBrand()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BrandGetResponseValidationError{
				field:  "Brand",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BrandGetResponseMultiError(errors)
	}

	return nil
}

// BrandGetResponseMultiError is an error wrapping multiple validation errors
// returned by BrandGetResponse.ValidateAll() if the designated constraints
// aren't met.
type BrandGetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BrandGetResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BrandGetResponseMultiError) AllErrors() []error { return m }

// BrandGetResponseValidationError is the validation error returned by
// BrandGetResponse.Validate if the designated constraints aren't met.
type BrandGetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BrandGetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BrandGetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BrandGetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BrandGetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BrandGetResponseValidationError) ErrorName() string { return "BrandGetResponseValidationError" }

// Error satisfies the builtin error interface
func (e BrandGetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBrandGetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BrandGetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BrandGetResponseValidationError{}

// Validate checks the field values on BrandUpdateMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BrandUpdateMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BrandUpdateMessage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BrandUpdateMessageMultiError, or nil if none found.
func (m *BrandUpdateMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *BrandUpdateMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Url

	if len(errors) > 0 {
		return BrandUpdateMessageMultiError(errors)
	}

	return nil
}

// BrandUpdateMessageMultiError is an error wrapping multiple validation errors
// returned by BrandUpdateMessage.ValidateAll() if the designated constraints
// aren't met.
type BrandUpdateMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BrandUpdateMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BrandUpdateMessageMultiError) AllErrors() []error { return m }

// BrandUpdateMessageValidationError is the validation error returned by
// BrandUpdateMessage.Validate if the designated constraints aren't met.
type BrandUpdateMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BrandUpdateMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BrandUpdateMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BrandUpdateMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BrandUpdateMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BrandUpdateMessageValidationError) ErrorName() string {
	return "BrandUpdateMessageValidationError"
}

// Error satisfies the builtin error interface
func (e BrandUpdateMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBrandUpdateMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BrandUpdateMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BrandUpdateMessageValidationError{}

// Validate checks the field values on BrandUpdateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BrandUpdateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BrandUpdateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BrandUpdateResponseMultiError, or nil if none found.
func (m *BrandUpdateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BrandUpdateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return BrandUpdateResponseMultiError(errors)
	}

	return nil
}

// BrandUpdateResponseMultiError is an error wrapping multiple validation
// errors returned by BrandUpdateResponse.ValidateAll() if the designated
// constraints aren't met.
type BrandUpdateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BrandUpdateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BrandUpdateResponseMultiError) AllErrors() []error { return m }

// BrandUpdateResponseValidationError is the validation error returned by
// BrandUpdateResponse.Validate if the designated constraints aren't met.
type BrandUpdateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BrandUpdateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BrandUpdateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BrandUpdateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BrandUpdateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BrandUpdateResponseValidationError) ErrorName() string {
	return "BrandUpdateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e BrandUpdateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBrandUpdateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BrandUpdateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BrandUpdateResponseValidationError{}
