// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/message/cache.proto

package message

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CacheCleanRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CacheCleanRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CacheCleanRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CacheCleanRequestMultiError, or nil if none found.
func (m *CacheCleanRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CacheCleanRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CacheCleanRequestMultiError(errors)
	}

	return nil
}

// CacheCleanRequestMultiError is an error wrapping multiple validation errors
// returned by CacheCleanRequest.ValidateAll() if the designated constraints
// aren't met.
type CacheCleanRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CacheCleanRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CacheCleanRequestMultiError) AllErrors() []error { return m }

// CacheCleanRequestValidationError is the validation error returned by
// CacheCleanRequest.Validate if the designated constraints aren't met.
type CacheCleanRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CacheCleanRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CacheCleanRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CacheCleanRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CacheCleanRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CacheCleanRequestValidationError) ErrorName() string {
	return "CacheCleanRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CacheCleanRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCacheCleanRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CacheCleanRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CacheCleanRequestValidationError{}

// Validate checks the field values on CacheCleanResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CacheCleanResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CacheCleanResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CacheCleanResponseMultiError, or nil if none found.
func (m *CacheCleanResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CacheCleanResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CacheCleanResponseMultiError(errors)
	}

	return nil
}

// CacheCleanResponseMultiError is an error wrapping multiple validation errors
// returned by CacheCleanResponse.ValidateAll() if the designated constraints
// aren't met.
type CacheCleanResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CacheCleanResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CacheCleanResponseMultiError) AllErrors() []error { return m }

// CacheCleanResponseValidationError is the validation error returned by
// CacheCleanResponse.Validate if the designated constraints aren't met.
type CacheCleanResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CacheCleanResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CacheCleanResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CacheCleanResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CacheCleanResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CacheCleanResponseValidationError) ErrorName() string {
	return "CacheCleanResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CacheCleanResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCacheCleanResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CacheCleanResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CacheCleanResponseValidationError{}
