// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/message/gateway.proto

package message

import (
	data "github.com/crevendo/crevendo/data"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewayListMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayListMessage) Reset() {
	*x = GatewayListMessage{}
	mi := &file_proto_message_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayListMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayListMessage) ProtoMessage() {}

func (x *GatewayListMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayListMessage.ProtoReflect.Descriptor instead.
func (*GatewayListMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayListMessage) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GatewayListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateways      []*data.Gateway        `protobuf:"bytes,1,rep,name=gateways,proto3" json:"gateways,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayListResponse) Reset() {
	*x = GatewayListResponse{}
	mi := &file_proto_message_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayListResponse) ProtoMessage() {}

func (x *GatewayListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayListResponse.ProtoReflect.Descriptor instead.
func (*GatewayListResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayListResponse) GetGateways() []*data.Gateway {
	if x != nil {
		return x.Gateways
	}
	return nil
}

var File_proto_message_gateway_proto protoreflect.FileDescriptor

const file_proto_message_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/message/gateway.proto\x1a\x13proto/gateway.proto\",\n" +
	"\x12GatewayListMessage\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\";\n" +
	"\x13GatewayListResponse\x12$\n" +
	"\bgateways\x18\x01 \x03(\v2\b.GatewayR\bgatewaysB&Z$github.com/crevendo/crevendo/messageb\x06proto3"

var (
	file_proto_message_gateway_proto_rawDescOnce sync.Once
	file_proto_message_gateway_proto_rawDescData []byte
)

func file_proto_message_gateway_proto_rawDescGZIP() []byte {
	file_proto_message_gateway_proto_rawDescOnce.Do(func() {
		file_proto_message_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_gateway_proto_rawDesc), len(file_proto_message_gateway_proto_rawDesc)))
	})
	return file_proto_message_gateway_proto_rawDescData
}

var file_proto_message_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_message_gateway_proto_goTypes = []any{
	(*GatewayListMessage)(nil),  // 0: GatewayListMessage
	(*GatewayListResponse)(nil), // 1: GatewayListResponse
	(*data.Gateway)(nil),        // 2: Gateway
}
var file_proto_message_gateway_proto_depIdxs = []int32{
	2, // 0: GatewayListResponse.gateways:type_name -> Gateway
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_message_gateway_proto_init() }
func file_proto_message_gateway_proto_init() {
	if File_proto_message_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_gateway_proto_rawDesc), len(file_proto_message_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_message_gateway_proto_goTypes,
		DependencyIndexes: file_proto_message_gateway_proto_depIdxs,
		MessageInfos:      file_proto_message_gateway_proto_msgTypes,
	}.Build()
	File_proto_message_gateway_proto = out.File
	file_proto_message_gateway_proto_goTypes = nil
	file_proto_message_gateway_proto_depIdxs = nil
}
