// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/message/integration.proto

package message

import (
	data "github.com/crevendo/crevendo/data"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntegrationListMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationListMessage) Reset() {
	*x = IntegrationListMessage{}
	mi := &file_proto_message_integration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationListMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationListMessage) ProtoMessage() {}

func (x *IntegrationListMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_integration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationListMessage.ProtoReflect.Descriptor instead.
func (*IntegrationListMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_integration_proto_rawDescGZIP(), []int{0}
}

type IntegrationListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Integrations  []*data.Integration    `protobuf:"bytes,1,rep,name=integrations,proto3" json:"integrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationListResponse) Reset() {
	*x = IntegrationListResponse{}
	mi := &file_proto_message_integration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationListResponse) ProtoMessage() {}

func (x *IntegrationListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_integration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationListResponse.ProtoReflect.Descriptor instead.
func (*IntegrationListResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_integration_proto_rawDescGZIP(), []int{1}
}

func (x *IntegrationListResponse) GetIntegrations() []*data.Integration {
	if x != nil {
		return x.Integrations
	}
	return nil
}

type IntegrationGetMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationGetMessage) Reset() {
	*x = IntegrationGetMessage{}
	mi := &file_proto_message_integration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationGetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationGetMessage) ProtoMessage() {}

func (x *IntegrationGetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_integration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationGetMessage.ProtoReflect.Descriptor instead.
func (*IntegrationGetMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_integration_proto_rawDescGZIP(), []int{2}
}

func (x *IntegrationGetMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IntegrationGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Integration   *data.Integration      `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationGetResponse) Reset() {
	*x = IntegrationGetResponse{}
	mi := &file_proto_message_integration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationGetResponse) ProtoMessage() {}

func (x *IntegrationGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_integration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationGetResponse.ProtoReflect.Descriptor instead.
func (*IntegrationGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_integration_proto_rawDescGZIP(), []int{3}
}

func (x *IntegrationGetResponse) GetIntegration() *data.Integration {
	if x != nil {
		return x.Integration
	}
	return nil
}

type IntegrationEnableMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationEnableMessage) Reset() {
	*x = IntegrationEnableMessage{}
	mi := &file_proto_message_integration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationEnableMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationEnableMessage) ProtoMessage() {}

func (x *IntegrationEnableMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_integration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationEnableMessage.ProtoReflect.Descriptor instead.
func (*IntegrationEnableMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_integration_proto_rawDescGZIP(), []int{4}
}

func (x *IntegrationEnableMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IntegrationEnableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationEnableResponse) Reset() {
	*x = IntegrationEnableResponse{}
	mi := &file_proto_message_integration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationEnableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationEnableResponse) ProtoMessage() {}

func (x *IntegrationEnableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_integration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationEnableResponse.ProtoReflect.Descriptor instead.
func (*IntegrationEnableResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_integration_proto_rawDescGZIP(), []int{5}
}

type IntegrationDisableMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationDisableMessage) Reset() {
	*x = IntegrationDisableMessage{}
	mi := &file_proto_message_integration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationDisableMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationDisableMessage) ProtoMessage() {}

func (x *IntegrationDisableMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_integration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationDisableMessage.ProtoReflect.Descriptor instead.
func (*IntegrationDisableMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_integration_proto_rawDescGZIP(), []int{6}
}

func (x *IntegrationDisableMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IntegrationDisableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationDisableResponse) Reset() {
	*x = IntegrationDisableResponse{}
	mi := &file_proto_message_integration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationDisableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationDisableResponse) ProtoMessage() {}

func (x *IntegrationDisableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_integration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationDisableResponse.ProtoReflect.Descriptor instead.
func (*IntegrationDisableResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_integration_proto_rawDescGZIP(), []int{7}
}

var File_proto_message_integration_proto protoreflect.FileDescriptor

const file_proto_message_integration_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/message/integration.proto\x1a\x17proto/integration.proto\"\x18\n" +
	"\x16IntegrationListMessage\"K\n" +
	"\x17IntegrationListResponse\x120\n" +
	"\fintegrations\x18\x01 \x03(\v2\f.IntegrationR\fintegrations\"'\n" +
	"\x15IntegrationGetMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"H\n" +
	"\x16IntegrationGetResponse\x12.\n" +
	"\vintegration\x18\x01 \x01(\v2\f.IntegrationR\vintegration\"*\n" +
	"\x18IntegrationEnableMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x1b\n" +
	"\x19IntegrationEnableResponse\"+\n" +
	"\x19IntegrationDisableMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x1c\n" +
	"\x1aIntegrationDisableResponseB&Z$github.com/crevendo/crevendo/messageb\x06proto3"

var (
	file_proto_message_integration_proto_rawDescOnce sync.Once
	file_proto_message_integration_proto_rawDescData []byte
)

func file_proto_message_integration_proto_rawDescGZIP() []byte {
	file_proto_message_integration_proto_rawDescOnce.Do(func() {
		file_proto_message_integration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_integration_proto_rawDesc), len(file_proto_message_integration_proto_rawDesc)))
	})
	return file_proto_message_integration_proto_rawDescData
}

var file_proto_message_integration_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_message_integration_proto_goTypes = []any{
	(*IntegrationListMessage)(nil),     // 0: IntegrationListMessage
	(*IntegrationListResponse)(nil),    // 1: IntegrationListResponse
	(*IntegrationGetMessage)(nil),      // 2: IntegrationGetMessage
	(*IntegrationGetResponse)(nil),     // 3: IntegrationGetResponse
	(*IntegrationEnableMessage)(nil),   // 4: IntegrationEnableMessage
	(*IntegrationEnableResponse)(nil),  // 5: IntegrationEnableResponse
	(*IntegrationDisableMessage)(nil),  // 6: IntegrationDisableMessage
	(*IntegrationDisableResponse)(nil), // 7: IntegrationDisableResponse
	(*data.Integration)(nil),           // 8: Integration
}
var file_proto_message_integration_proto_depIdxs = []int32{
	8, // 0: IntegrationListResponse.integrations:type_name -> Integration
	8, // 1: IntegrationGetResponse.integration:type_name -> Integration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_message_integration_proto_init() }
func file_proto_message_integration_proto_init() {
	if File_proto_message_integration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_integration_proto_rawDesc), len(file_proto_message_integration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_message_integration_proto_goTypes,
		DependencyIndexes: file_proto_message_integration_proto_depIdxs,
		MessageInfos:      file_proto_message_integration_proto_msgTypes,
	}.Build()
	File_proto_message_integration_proto = out.File
	file_proto_message_integration_proto_goTypes = nil
	file_proto_message_integration_proto_depIdxs = nil
}
