// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/message/product.proto

package message

import (
	data "github.com/crevendo/crevendo/data"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductGetMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	CustomId      *string                `protobuf:"bytes,2,opt,name=customId,proto3,oneof" json:"customId,omitempty"`
	WithVariants  *bool                  `protobuf:"varint,3,opt,name=withVariants,proto3,oneof" json:"withVariants,omitempty"`
	IgnoreCache   *bool                  `protobuf:"varint,4,opt,name=ignoreCache,proto3,oneof" json:"ignoreCache,omitempty"`
	Preloads      []string               `protobuf:"bytes,5,rep,name=preloads,proto3" json:"preloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductGetMessage) Reset() {
	*x = ProductGetMessage{}
	mi := &file_proto_message_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductGetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductGetMessage) ProtoMessage() {}

func (x *ProductGetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductGetMessage.ProtoReflect.Descriptor instead.
func (*ProductGetMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductGetMessage) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *ProductGetMessage) GetCustomId() string {
	if x != nil && x.CustomId != nil {
		return *x.CustomId
	}
	return ""
}

func (x *ProductGetMessage) GetWithVariants() bool {
	if x != nil && x.WithVariants != nil {
		return *x.WithVariants
	}
	return false
}

func (x *ProductGetMessage) GetIgnoreCache() bool {
	if x != nil && x.IgnoreCache != nil {
		return *x.IgnoreCache
	}
	return false
}

func (x *ProductGetMessage) GetPreloads() []string {
	if x != nil {
		return x.Preloads
	}
	return nil
}

type ProductGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *data.Product          `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductGetResponse) Reset() {
	*x = ProductGetResponse{}
	mi := &file_proto_message_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductGetResponse) ProtoMessage() {}

func (x *ProductGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductGetResponse.ProtoReflect.Descriptor instead.
func (*ProductGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductGetResponse) GetProduct() *data.Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ProductListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*data.Product        `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Page          *int32                 `protobuf:"varint,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageTotal     *int32                 `protobuf:"varint,3,opt,name=pageTotal,proto3,oneof" json:"pageTotal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductListResponse) Reset() {
	*x = ProductListResponse{}
	mi := &file_proto_message_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductListResponse) ProtoMessage() {}

func (x *ProductListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductListResponse.ProtoReflect.Descriptor instead.
func (*ProductListResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductListResponse) GetProducts() []*data.Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ProductListResponse) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ProductListResponse) GetPageTotal() int32 {
	if x != nil && x.PageTotal != nil {
		return *x.PageTotal
	}
	return 0
}

type ProductListMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	CustomIds     []string               `protobuf:"bytes,2,rep,name=customIds,proto3" json:"customIds,omitempty"`
	CategoryId    *int32                 `protobuf:"varint,3,opt,name=categoryId,proto3,oneof" json:"categoryId,omitempty"`
	Type          *string                `protobuf:"bytes,4,opt,name=type,proto3,oneof" json:"type,omitempty"`
	SearchTerm    *string                `protobuf:"bytes,6,opt,name=searchTerm,proto3,oneof" json:"searchTerm,omitempty"`
	Page          *int32                 `protobuf:"varint,7,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Limit         *int32                 `protobuf:"varint,8,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	OrderBy       *string                `protobuf:"bytes,9,opt,name=orderBy,proto3,oneof" json:"orderBy,omitempty"`
	IgnoreCache   *bool                  `protobuf:"varint,10,opt,name=ignoreCache,proto3,oneof" json:"ignoreCache,omitempty"`
	SessionUUID   *string                `protobuf:"bytes,11,opt,name=sessionUUID,proto3,oneof" json:"sessionUUID,omitempty"`
	TimeLimit     *int32                 `protobuf:"varint,12,opt,name=timeLimit,proto3,oneof" json:"timeLimit,omitempty"`
	Preloads      []string               `protobuf:"bytes,13,rep,name=preloads,proto3" json:"preloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductListMessage) Reset() {
	*x = ProductListMessage{}
	mi := &file_proto_message_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductListMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductListMessage) ProtoMessage() {}

func (x *ProductListMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductListMessage.ProtoReflect.Descriptor instead.
func (*ProductListMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductListMessage) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ProductListMessage) GetCustomIds() []string {
	if x != nil {
		return x.CustomIds
	}
	return nil
}

func (x *ProductListMessage) GetCategoryId() int32 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *ProductListMessage) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *ProductListMessage) GetSearchTerm() string {
	if x != nil && x.SearchTerm != nil {
		return *x.SearchTerm
	}
	return ""
}

func (x *ProductListMessage) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ProductListMessage) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ProductListMessage) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *ProductListMessage) GetIgnoreCache() bool {
	if x != nil && x.IgnoreCache != nil {
		return *x.IgnoreCache
	}
	return false
}

func (x *ProductListMessage) GetSessionUUID() string {
	if x != nil && x.SessionUUID != nil {
		return *x.SessionUUID
	}
	return ""
}

func (x *ProductListMessage) GetTimeLimit() int32 {
	if x != nil && x.TimeLimit != nil {
		return *x.TimeLimit
	}
	return 0
}

func (x *ProductListMessage) GetPreloads() []string {
	if x != nil {
		return x.Preloads
	}
	return nil
}

type ProductUpdateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Excerpt       string                 `protobuf:"bytes,6,opt,name=excerpt,proto3" json:"excerpt,omitempty"`
	BrandId       int32                  `protobuf:"varint,7,opt,name=brandId,proto3" json:"brandId,omitempty"`
	Stock         int32                  `protobuf:"varint,8,opt,name=stock,proto3" json:"stock,omitempty"`
	Images        []string               `protobuf:"bytes,9,rep,name=images,proto3" json:"images,omitempty"`
	CategoriesIds []int32                `protobuf:"varint,10,rep,packed,name=categoriesIds,proto3" json:"categoriesIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductUpdateMessage) Reset() {
	*x = ProductUpdateMessage{}
	mi := &file_proto_message_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUpdateMessage) ProtoMessage() {}

func (x *ProductUpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUpdateMessage.ProtoReflect.Descriptor instead.
func (*ProductUpdateMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_product_proto_rawDescGZIP(), []int{4}
}

func (x *ProductUpdateMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductUpdateMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductUpdateMessage) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductUpdateMessage) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProductUpdateMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductUpdateMessage) GetExcerpt() string {
	if x != nil {
		return x.Excerpt
	}
	return ""
}

func (x *ProductUpdateMessage) GetBrandId() int32 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *ProductUpdateMessage) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductUpdateMessage) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ProductUpdateMessage) GetCategoriesIds() []int32 {
	if x != nil {
		return x.CategoriesIds
	}
	return nil
}

type ProductUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *data.Product          `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductUpdateResponse) Reset() {
	*x = ProductUpdateResponse{}
	mi := &file_proto_message_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUpdateResponse) ProtoMessage() {}

func (x *ProductUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUpdateResponse.ProtoReflect.Descriptor instead.
func (*ProductUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_product_proto_rawDescGZIP(), []int{5}
}

func (x *ProductUpdateResponse) GetProduct() *data.Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ProductCreateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Excerpt       string                 `protobuf:"bytes,5,opt,name=excerpt,proto3" json:"excerpt,omitempty"`
	BrandId       int32                  `protobuf:"varint,6,opt,name=brandId,proto3" json:"brandId,omitempty"`
	Stock         int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	Images        []string               `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`
	CategoriesIds []int32                `protobuf:"varint,9,rep,packed,name=categoriesIds,proto3" json:"categoriesIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCreateMessage) Reset() {
	*x = ProductCreateMessage{}
	mi := &file_proto_message_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCreateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCreateMessage) ProtoMessage() {}

func (x *ProductCreateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCreateMessage.ProtoReflect.Descriptor instead.
func (*ProductCreateMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_product_proto_rawDescGZIP(), []int{6}
}

func (x *ProductCreateMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductCreateMessage) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProductCreateMessage) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductCreateMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductCreateMessage) GetExcerpt() string {
	if x != nil {
		return x.Excerpt
	}
	return ""
}

func (x *ProductCreateMessage) GetBrandId() int32 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *ProductCreateMessage) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductCreateMessage) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ProductCreateMessage) GetCategoriesIds() []int32 {
	if x != nil {
		return x.CategoriesIds
	}
	return nil
}

type ProductCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *data.Product          `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCreateResponse) Reset() {
	*x = ProductCreateResponse{}
	mi := &file_proto_message_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCreateResponse) ProtoMessage() {}

func (x *ProductCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCreateResponse.ProtoReflect.Descriptor instead.
func (*ProductCreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_product_proto_rawDescGZIP(), []int{7}
}

func (x *ProductCreateResponse) GetProduct() *data.Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ProductDeleteMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDeleteMessage) Reset() {
	*x = ProductDeleteMessage{}
	mi := &file_proto_message_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDeleteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDeleteMessage) ProtoMessage() {}

func (x *ProductDeleteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDeleteMessage.ProtoReflect.Descriptor instead.
func (*ProductDeleteMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_product_proto_rawDescGZIP(), []int{8}
}

func (x *ProductDeleteMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProductDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDeleteResponse) Reset() {
	*x = ProductDeleteResponse{}
	mi := &file_proto_message_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDeleteResponse) ProtoMessage() {}

func (x *ProductDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDeleteResponse.ProtoReflect.Descriptor instead.
func (*ProductDeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_product_proto_rawDescGZIP(), []int{9}
}

func (x *ProductDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_message_product_proto protoreflect.FileDescriptor

const file_proto_message_product_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/message/product.proto\x1a\x14proto/validate.proto\x1a\x13proto/product.proto\"\xf3\x01\n" +
	"\x11ProductGetMessage\x12\x1c\n" +
	"\x02id\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00H\x00R\x02id\x88\x01\x01\x12\x1f\n" +
	"\bcustomId\x18\x02 \x01(\tH\x01R\bcustomId\x88\x01\x01\x12'\n" +
	"\fwithVariants\x18\x03 \x01(\bH\x02R\fwithVariants\x88\x01\x01\x12%\n" +
	"\vignoreCache\x18\x04 \x01(\bH\x03R\vignoreCache\x88\x01\x01\x12\x1a\n" +
	"\bpreloads\x18\x05 \x03(\tR\bpreloadsB\x05\n" +
	"\x03_idB\v\n" +
	"\t_customIdB\x0f\n" +
	"\r_withVariantsB\x0e\n" +
	"\f_ignoreCache\"8\n" +
	"\x12ProductGetResponse\x12\"\n" +
	"\aproduct\x18\x01 \x01(\v2\b.ProductR\aproduct\"\x8e\x01\n" +
	"\x13ProductListResponse\x12$\n" +
	"\bproducts\x18\x01 \x03(\v2\b.ProductR\bproducts\x12\x17\n" +
	"\x04page\x18\x02 \x01(\x05H\x00R\x04page\x88\x01\x01\x12!\n" +
	"\tpageTotal\x18\x03 \x01(\x05H\x01R\tpageTotal\x88\x01\x01B\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_pageTotal\"\xfb\x03\n" +
	"\x12ProductListMessage\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\x12\x1c\n" +
	"\tcustomIds\x18\x02 \x03(\tR\tcustomIds\x12#\n" +
	"\n" +
	"categoryId\x18\x03 \x01(\x05H\x00R\n" +
	"categoryId\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x04 \x01(\tH\x01R\x04type\x88\x01\x01\x12#\n" +
	"\n" +
	"searchTerm\x18\x06 \x01(\tH\x02R\n" +
	"searchTerm\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\a \x01(\x05H\x03R\x04page\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\b \x01(\x05H\x04R\x05limit\x88\x01\x01\x12\x1d\n" +
	"\aorderBy\x18\t \x01(\tH\x05R\aorderBy\x88\x01\x01\x12%\n" +
	"\vignoreCache\x18\n" +
	" \x01(\bH\x06R\vignoreCache\x88\x01\x01\x12%\n" +
	"\vsessionUUID\x18\v \x01(\tH\aR\vsessionUUID\x88\x01\x01\x12!\n" +
	"\ttimeLimit\x18\f \x01(\x05H\bR\ttimeLimit\x88\x01\x01\x12\x1a\n" +
	"\bpreloads\x18\r \x03(\tR\bpreloadsB\r\n" +
	"\v_categoryIdB\a\n" +
	"\x05_typeB\r\n" +
	"\v_searchTermB\a\n" +
	"\x05_pageB\b\n" +
	"\x06_limitB\n" +
	"\n" +
	"\b_orderByB\x0e\n" +
	"\f_ignoreCacheB\x0e\n" +
	"\f_sessionUUIDB\f\n" +
	"\n" +
	"_timeLimit\"\x90\x02\n" +
	"\x14ProductUpdateMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\aexcerpt\x18\x06 \x01(\tR\aexcerpt\x12\x18\n" +
	"\abrandId\x18\a \x01(\x05R\abrandId\x12\x14\n" +
	"\x05stock\x18\b \x01(\x05R\x05stock\x12\x16\n" +
	"\x06images\x18\t \x03(\tR\x06images\x12$\n" +
	"\rcategoriesIds\x18\n" +
	" \x03(\x05R\rcategoriesIds\";\n" +
	"\x15ProductUpdateResponse\x12\"\n" +
	"\aproduct\x18\x01 \x01(\v2\b.ProductR\aproduct\"\x80\x02\n" +
	"\x14ProductCreateMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aexcerpt\x18\x05 \x01(\tR\aexcerpt\x12\x18\n" +
	"\abrandId\x18\x06 \x01(\x05R\abrandId\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12\x16\n" +
	"\x06images\x18\b \x03(\tR\x06images\x12$\n" +
	"\rcategoriesIds\x18\t \x03(\x05R\rcategoriesIds\";\n" +
	"\x15ProductCreateResponse\x12\"\n" +
	"\aproduct\x18\x01 \x01(\v2\b.ProductR\aproduct\"&\n" +
	"\x14ProductDeleteMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"1\n" +
	"\x15ProductDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB&Z$github.com/crevendo/crevendo/messageb\x06proto3"

var (
	file_proto_message_product_proto_rawDescOnce sync.Once
	file_proto_message_product_proto_rawDescData []byte
)

func file_proto_message_product_proto_rawDescGZIP() []byte {
	file_proto_message_product_proto_rawDescOnce.Do(func() {
		file_proto_message_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_product_proto_rawDesc), len(file_proto_message_product_proto_rawDesc)))
	})
	return file_proto_message_product_proto_rawDescData
}

var file_proto_message_product_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_message_product_proto_goTypes = []any{
	(*ProductGetMessage)(nil),     // 0: ProductGetMessage
	(*ProductGetResponse)(nil),    // 1: ProductGetResponse
	(*ProductListResponse)(nil),   // 2: ProductListResponse
	(*ProductListMessage)(nil),    // 3: ProductListMessage
	(*ProductUpdateMessage)(nil),  // 4: ProductUpdateMessage
	(*ProductUpdateResponse)(nil), // 5: ProductUpdateResponse
	(*ProductCreateMessage)(nil),  // 6: ProductCreateMessage
	(*ProductCreateResponse)(nil), // 7: ProductCreateResponse
	(*ProductDeleteMessage)(nil),  // 8: ProductDeleteMessage
	(*ProductDeleteResponse)(nil), // 9: ProductDeleteResponse
	(*data.Product)(nil),          // 10: Product
}
var file_proto_message_product_proto_depIdxs = []int32{
	10, // 0: ProductGetResponse.product:type_name -> Product
	10, // 1: ProductListResponse.products:type_name -> Product
	10, // 2: ProductUpdateResponse.product:type_name -> Product
	10, // 3: ProductCreateResponse.product:type_name -> Product
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_message_product_proto_init() }
func file_proto_message_product_proto_init() {
	if File_proto_message_product_proto != nil {
		return
	}
	file_proto_message_product_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_message_product_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_message_product_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_product_proto_rawDesc), len(file_proto_message_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_message_product_proto_goTypes,
		DependencyIndexes: file_proto_message_product_proto_depIdxs,
		MessageInfos:      file_proto_message_product_proto_msgTypes,
	}.Build()
	File_proto_message_product_proto = out.File
	file_proto_message_product_proto_goTypes = nil
	file_proto_message_product_proto_depIdxs = nil
}
