// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/message/session.proto

package message

import (
	data "github.com/crevendo/crevendo/data"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionCreateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCreateMessage) Reset() {
	*x = SessionCreateMessage{}
	mi := &file_proto_message_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCreateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCreateMessage) ProtoMessage() {}

func (x *SessionCreateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCreateMessage.ProtoReflect.Descriptor instead.
func (*SessionCreateMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_session_proto_rawDescGZIP(), []int{0}
}

type SessionCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *data.Session          `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCreateResponse) Reset() {
	*x = SessionCreateResponse{}
	mi := &file_proto_message_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCreateResponse) ProtoMessage() {}

func (x *SessionCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCreateResponse.ProtoReflect.Descriptor instead.
func (*SessionCreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_session_proto_rawDescGZIP(), []int{1}
}

func (x *SessionCreateResponse) GetSession() *data.Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type SessionGetMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionGetMessage) Reset() {
	*x = SessionGetMessage{}
	mi := &file_proto_message_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionGetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionGetMessage) ProtoMessage() {}

func (x *SessionGetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionGetMessage.ProtoReflect.Descriptor instead.
func (*SessionGetMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_session_proto_rawDescGZIP(), []int{2}
}

func (x *SessionGetMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type SessionGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *data.Session          `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionGetResponse) Reset() {
	*x = SessionGetResponse{}
	mi := &file_proto_message_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionGetResponse) ProtoMessage() {}

func (x *SessionGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionGetResponse.ProtoReflect.Descriptor instead.
func (*SessionGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_session_proto_rawDescGZIP(), []int{3}
}

func (x *SessionGetResponse) GetSession() *data.Session {
	if x != nil {
		return x.Session
	}
	return nil
}

var File_proto_message_session_proto protoreflect.FileDescriptor

const file_proto_message_session_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/message/session.proto\x1a\x13proto/session.proto\"\x16\n" +
	"\x14SessionCreateMessage\";\n" +
	"\x15SessionCreateResponse\x12\"\n" +
	"\asession\x18\x01 \x01(\v2\b.SessionR\asession\"'\n" +
	"\x11SessionGetMessage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"8\n" +
	"\x12SessionGetResponse\x12\"\n" +
	"\asession\x18\x01 \x01(\v2\b.SessionR\asessionB&Z$github.com/crevendo/crevendo/messageb\x06proto3"

var (
	file_proto_message_session_proto_rawDescOnce sync.Once
	file_proto_message_session_proto_rawDescData []byte
)

func file_proto_message_session_proto_rawDescGZIP() []byte {
	file_proto_message_session_proto_rawDescOnce.Do(func() {
		file_proto_message_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_session_proto_rawDesc), len(file_proto_message_session_proto_rawDesc)))
	})
	return file_proto_message_session_proto_rawDescData
}

var file_proto_message_session_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_message_session_proto_goTypes = []any{
	(*SessionCreateMessage)(nil),  // 0: SessionCreateMessage
	(*SessionCreateResponse)(nil), // 1: SessionCreateResponse
	(*SessionGetMessage)(nil),     // 2: SessionGetMessage
	(*SessionGetResponse)(nil),    // 3: SessionGetResponse
	(*data.Session)(nil),          // 4: Session
}
var file_proto_message_session_proto_depIdxs = []int32{
	4, // 0: SessionCreateResponse.session:type_name -> Session
	4, // 1: SessionGetResponse.session:type_name -> Session
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_message_session_proto_init() }
func file_proto_message_session_proto_init() {
	if File_proto_message_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_session_proto_rawDesc), len(file_proto_message_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_message_session_proto_goTypes,
		DependencyIndexes: file_proto_message_session_proto_depIdxs,
		MessageInfos:      file_proto_message_session_proto_msgTypes,
	}.Build()
	File_proto_message_session_proto = out.File
	file_proto_message_session_proto_goTypes = nil
	file_proto_message_session_proto_depIdxs = nil
}
